CREATE TABLE `MEMBER` (
	`USER_ID`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field12`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`Field14`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL,
	`Field13`	VARCHAR(255)	NULL	COMMENT '애매-',
	`Field6`	VARCHAR(255)	NULL	COMMENT '해미',
	`Field11`	VARCHAR(255)	NULL	COMMENT '애매-',
	`Field7`	VARCHAR(255)	NULL	COMMENT '탈퇴 계정, 백업 테이블 고민',
	`Field8`	VARCHAR(255)	NULL,
	`Field9`	VARCHAR(255)	NULL,
	`Field10`	VARCHAR(255)	NULL
);

CREATE TABLE `BOARD` (
	`BOARD_ID`	VARCHAR(255)	NOT NULL,
	`USER_ID`	VARCHAR(255)	NOT NULL,
	`CATEGORY_ID`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL
);

CREATE TABLE `OWNER` (
	`OWNER_ID`	VARCHAR(255)	NOT NULL,
	`USER_ID`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL
);

CREATE TABLE `EXERCISE_RECORD` (
	`Key`	VARCHAR(255)	NOT NULL,
	`USER_ID`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL
);

CREATE TABLE `TRAINER` (
	`TRAINER_ID`	VARCHAR(255)	NOT NULL,
	`USER_ID`	VARCHAR(255)	NOT NULL,
	`GYM_ID`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL	COMMENT '이미지',
	`Field4`	VARCHAR(255)	NULL	COMMENT '이미지',
	`Field5`	VARCHAR(255)	NULL	COMMENT '카운트',
	`Field6`	VARCHAR(255)	NULL	COMMENT '카운트',
	`Field7`	VARCHAR(255)	NULL,
	`Field8`	VARCHAR(255)	NULL
);

CREATE TABLE `CHAT` (
	`CHAT_ID`	VARCHAR(255)	NOT NULL,
	`LAST_MSG`	VARCHAR(255)	NULL,
	`CREATE_AT`	VARCHAR(255)	NULL,
	`HOST_ID`	VARCHAR(255)	NOT NULL,
	`GUEST_ID`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `CATEGORY` (
	`CATEGORY_ID`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

CREATE TABLE `COMMENT_BOARD` (
	`COMMENT_BOARD_ID`	VARCHAR(255)	NOT NULL,
	`USER_ID`	VARCHAR(255)	NOT NULL,
	`BOARD_ID`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `COMMENT_TRAINER` (
	`COMMENT_TRAINER_ID`	VARCHAR(255)	NOT NULL,
	`USER_ID`	VARCHAR(255)	NOT NULL,
	`TRAINER_ID`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL
);

CREATE TABLE `COMMENT_GYM` (
	`COMMENT_GYM_ID`	VARCHAR(255)	NOT NULL,
	`USER_ID`	VARCHAR(255)	NOT NULL,
	`GYM_ID`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL
);

CREATE TABLE `GYM` (
	`GYM_ID`	VARCHAR(255)	NOT NULL,
	`OWNER_ID`	VARCHAR(255)	NOT NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field8`	VARCHAR(255)	NULL,
	`Field6`	VARCHAR(255)	NULL,
	`Field7`	VARCHAR(255)	NULL,
	`Field9`	VARCHAR(255)	NULL,
	`Field10`	VARCHAR(255)	NULL,
	`Field11`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL
);

CREATE TABLE `ROOM_TRAINER` (
	`ROOM_TRAINER_ID`	VARCHAR(255)	NOT NULL,
	`TRAINER_ID`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field7`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL,
	`Field6`	VARCHAR(255)	NULL
);

CREATE TABLE `ROOM_USER` (
	`ROOM_USER_ID`	VARCHAR(255)	NOT NULL,
	`GROUP_LEADER_ID`	VARCHAR(255)	NOT NULL	COMMENT '방 : 그룹장 = 1 : 1',
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL,
	`Field4`	VARCHAR(255)	NULL,
	`Field5`	VARCHAR(255)	NULL,
	`Field6`	VARCHAR(255)	NULL,
	`Field7`	VARCHAR(255)	NULL
);

CREATE TABLE `ROOM_TRAINER_PARTI` (
	`RTP_ID`	VARCHAR(255)	NOT NULL,
	`ROOM_ID`	VARCHAR(255)	NOT NULL,
	`USER_ID`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL
);

CREATE TABLE `ROOM_USER_PARTI` (
	`RUP_ID`	VARCHAR(255)	NOT NULL,
	`ROOM_ID`	VARCHAR(255)	NOT NULL,
	`USER_ID`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL
);

CREATE TABLE `FAVORITE_TRAINER` (
	`Key`	VARCHAR(255)	NOT NULL,
	`TRAINER_ID`	VARCHAR(255)	NOT NULL,
	`USER_ID`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL
);

CREATE TABLE `FAVORITE_GYM` (
	`Key`	VARCHAR(255)	NOT NULL,
	`GYM_ID`	VARCHAR(255)	NOT NULL,
	`USER_ID`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL
);

CREATE TABLE `BOARD_IMAGE` (
	`IMAGE_ID`	VARCHAR(255)	NOT NULL,
	`BOARD_ID`	VARCHAR(255)	NOT NULL,
	`Field`	VARCHAR(255)	NULL,
	`Field2`	VARCHAR(255)	NULL,
	`Field3`	VARCHAR(255)	NULL
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`USER_ID`
);

ALTER TABLE `BOARD` ADD CONSTRAINT `PK_BOARD` PRIMARY KEY (
	`BOARD_ID`
);

ALTER TABLE `OWNER` ADD CONSTRAINT `PK_OWNER` PRIMARY KEY (
	`OWNER_ID`
);

ALTER TABLE `EXERCISE_RECORD` ADD CONSTRAINT `PK_EXERCISE_RECORD` PRIMARY KEY (
	`Key`
);

ALTER TABLE `TRAINER` ADD CONSTRAINT `PK_TRAINER` PRIMARY KEY (
	`TRAINER_ID`
);

ALTER TABLE `CHAT` ADD CONSTRAINT `PK_CHAT` PRIMARY KEY (
	`CHAT_ID`
);

ALTER TABLE `CATEGORY` ADD CONSTRAINT `PK_CATEGORY` PRIMARY KEY (
	`CATEGORY_ID`
);

ALTER TABLE `COMMENT_BOARD` ADD CONSTRAINT `PK_COMMENT_BOARD` PRIMARY KEY (
	`COMMENT_BOARD_ID`
);

ALTER TABLE `COMMENT_TRAINER` ADD CONSTRAINT `PK_COMMENT_TRAINER` PRIMARY KEY (
	`COMMENT_TRAINER_ID`
);

ALTER TABLE `COMMENT_GYM` ADD CONSTRAINT `PK_COMMENT_GYM` PRIMARY KEY (
	`COMMENT_GYM_ID`
);

ALTER TABLE `GYM` ADD CONSTRAINT `PK_GYM` PRIMARY KEY (
	`GYM_ID`
);

ALTER TABLE `ROOM_TRAINER` ADD CONSTRAINT `PK_ROOM_TRAINER` PRIMARY KEY (
	`ROOM_TRAINER_ID`
);

ALTER TABLE `ROOM_USER` ADD CONSTRAINT `PK_ROOM_USER` PRIMARY KEY (
	`ROOM_USER_ID`
);

ALTER TABLE `ROOM_TRAINER_PARTI` ADD CONSTRAINT `PK_ROOM_TRAINER_PARTI` PRIMARY KEY (
	`RTP_ID`
);

ALTER TABLE `ROOM_USER_PARTI` ADD CONSTRAINT `PK_ROOM_USER_PARTI` PRIMARY KEY (
	`RUP_ID`
);

ALTER TABLE `FAVORITE_TRAINER` ADD CONSTRAINT `PK_FAVORITE_TRAINER` PRIMARY KEY (
	`Key`
);

ALTER TABLE `FAVORITE_GYM` ADD CONSTRAINT `PK_FAVORITE_GYM` PRIMARY KEY (
	`Key`
);

ALTER TABLE `BOARD_IMAGE` ADD CONSTRAINT `PK_BOARD_IMAGE` PRIMARY KEY (
	`IMAGE_ID`
);

